### PR TITLE
Vertex/edge cutting

### PR DESCRIPTION
**Pull request by mjsutcliffe99**
Included functions for applying the vertex and edge cutting decompositions

### CODE REVIEW

**Comment by mjsutcliffe99** [comment]
> Can you please add tests?

I've just added some tests for both functions to verify the scalar results are correct on randomly generated graphs

**Comment by jvdwetering** [comment]
Could you add docstrings to the main functions you added, with perhaps a reference to your papers where you use them.

**Comment by jvdwetering** [comment]
Ah I see what goes wrong. You are using match statements, but these were introduced in Python 3.10. PyZX still supports older versions of Python. I see that in that match statement you are also using hard-coded `1` and `2` for the types of Z and X spiders. You can actually replace this by calling the function `utils.toggle_vertex` for the same functionality.

**Comment by jvdwetering** [comment]
Can this be merged?

**Pull request merged**
