### PR TITLE
Setup formatter

### LINKED ISSUE #232: Coding style
I'm now planning to contribute to this repo., but before I proceed, I would like to ask about the coding style.

- Is there any kind of style guideline for this repo?
- If any, is it different from the Python standard (PEP8)?
- Do you have any plans for using formatter like `black` or `ruff format` ?

### PR DESCRIPTION
**Pull request by EarlMilktea**
Resolves #232 .

### CODE REVIEW

**Comment by EarlMilktea** [comment]
MEMO: This config. is optional (defaults to `88`)

```toml
line-length = 120
```

**Comment by dlyongemallo** [comment]
> Resolves #232 .

Resolves #122.

**Comment by akissinger** [comment]
I'm not sure about this, mainly just because I've never used auto-formatting at this level before.

It looks like this could potentially spam the commit logs by creating a double commit for almost everything. One is the actual commit, then a second commit e.g. putting a bit less/more whitespace somewhere because someone's editor isn't configured in the same way as ruff. Is consistent formatting worth the extra commit spam and/or effort? (genuine question, not a rhetorical one)

**Comment by EarlMilktea** [comment]
@akissinger (CC: @jvdwetering )

Let me first note that formatter CI does **NOT** run each time you commit: only once per merged PR because it's tracking master branch only.

Actually I admit Ruff (or black similarly) is sometimes too strict, but at the same time, it helps me a lot because...

- Contributors don't have to care about the coding style or consult coding style document
- Reviewer-friendly as diffs. are minimized, also easy to grep
- Reviewers don't have to manually check that the codes are PEP8-compliant
- Can detect unconventional styles: for example

```python
if x: break
```

- Simplifies linter/editor configuration since we don't have to manually inspect which rules are associated with PEP8 

If you're not happy with automatic commit, I'm willing to rewrite the CI to just report problems and urge contributors to fix.
Which do you prefer?

**Comment by dlyongemallo** [comment]
> Is consistent formatting worth the extra commit spam and/or effort? (genuine question, not a rhetorical one)

In a large code base touched by many people, a consistent style make certain tasks easier or more pleasant. Reading unfamiliar code in which the style switches between code blocks imposes an unnecessary cognitive load because the reader has to think about whether apparent differences are meaningful.

Extra commits can probably be reduced by documenting the expected style in the contributor guidelines and encouraging contributors to use automatic formatting tools (e.g., format on save in their editor).

**Comment by dlyongemallo** [comment]
@EarlMilktea Why was this closed? I'd like to see something like this implemented.

**Pull request closed without merging**
