### PR TITLE
return an empty generator when there are no edges between source and target

### PR DESCRIPTION
**Pull request by RazinShaikh**
This fixes some keyerror exceptions

### CODE REVIEW

**Comment by jvdwetering** [comment]
You write
```return
yield```
How does that work? Shouldn't it just be `yield` if you want to return a generator. Or am I misunderstanding how empty generators work. If so, maybe add a comment that this is intentionally returning an empty generator?

**Comment by RazinShaikh** [comment]
I don't really understand why exactly this returns an empty generator. I got it from this stackoverflow answer with 200 votes. Without the yield, the return statement returns None instead of a generator.

https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function

**Comment by RazinShaikh** [comment]
I don't really understand why exactly this returns an empty generator. I got it from this stackoverflow answer with 200 votes.

https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function

**Comment by RazinShaikh** [comment]
I misunderstood the stackoverflow answer. The yield statement is unnecessary; pushed the correction.

**Pull request merged**
